<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_56921411d5102',
  'title' => '_Sellaporter',
  'fields' => array (
    array (
      'key' => 'field_569215f3fa9ae',
      'label' => 'Sales Page Content',
      'name' => 'sales_page_content',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_568e4bf132aeb',
      'label' => 'Smart Sales Page',
      'name' => 'smart_sales_page',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Section',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '56921411f0742',
          'name' => 'sp-hero',
          'label' => 'Hero',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_56973cb7caee5',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_568e4c5332aec',
              'label' => 'Choose the type of hero box:',
              'name' => 'hero_type',
              'type' => 'radio',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'super' => 'Super Heading',
                'normal' => 'Regular Heading',
              ),
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => 'normal',
              'layout' => 'horizontal',
            ),
            array (
              'key' => 'field_568e4cb332aed',
              'label' => 'Product Name',
              'name' => 'superheading',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_568e4c5332aec',
                    'operator' => '==',
                    'value' => 'super',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_568e4cd832aee',
              'label' => 'Page Heading',
              'name' => 'subtitle',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_568e4c5332aec',
                    'operator' => '==',
                    'value' => 'super',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_568e4cea32aef',
              'label' => 'Heading',
              'name' => 'heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_568e4c5332aec',
                    'operator' => '==',
                    'value' => 'normal',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'none',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_568e4cf932af0',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_568e4d5632af1',
              'label' => 'Background Image',
              'name' => 'background_image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'large',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_568e4dbd32af2',
              'label' => 'Image Tint',
              'name' => 'image_tint',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'none' => 'None',
                'medium' => 'Medium',
                'dark' => 'Dark',
              ),
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => '',
              'layout' => 'horizontal',
            ),
            array (
              'key' => 'field_568e4df332af3',
              'label' => 'Text Options',
              'name' => 'text_options',
              'type' => 'checkbox',
              'instructions' => 'Check boxes to apply effects to the text in the hero box.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'shadow' => 'Text Shadow',
                'inverted' => 'Invert Colors',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 0,
            ),
            array (
              'key' => 'field_5690c204489bb',
              'label' => 'Show CTA Button?',
              'name' => 'show_cta_button',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => 'If true, the hero box will have a button to click.',
              'default_value' => 0,
            ),
            array (
              'key' => 'field_569a1891c0ea2',
              'label' => 'What happens when the CTA button is clicked?',
              'name' => 'cta_type',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'popover' => 'A pop-over box displays.',
                'page' => 'The user goes to a new page.',
              ),
              'default_value' => array (
                'page' => 'page',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_5690c267ea193',
              'label' => 'Button Text',
              'name' => 'button_text',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5690c204489bb',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_5690c277ea194',
              'label' => 'Button Link',
              'name' => 'button_link',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5690c204489bb',
                    'operator' => '==',
                    'value' => '1',
                  ),
                  array (
                    'field' => 'field_569a1891c0ea2',
                    'operator' => '==',
                    'value' => 'page',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'http://',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5692141244d6e',
          'name' => 'sp-generic',
          'label' => 'Freestyle Content Box',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_569de1d6e0e27',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_5690e7ad0202c',
              'label' => 'Body Text',
              'name' => 'body_text',
              'type' => 'wysiwyg',
              'instructions' => 'Put anything you want in here. No rules, boss!',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'toolbar' => 'full',
              'media_upload' => 1,
              'tabs' => 'all',
            ),
            array (
              'key' => 'field_5690e7d00202d',
              'label' => 'Section Alignment',
              'name' => 'alignment',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'center' => 'Center',
                'left' => 'Left',
                'right' => 'Right',
              ),
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => 'center',
              'layout' => 'horizontal',
            ),
            array (
              'key' => 'field_5690e8090202e',
              'label' => 'Background Image',
              'name' => 'background_image',
              'type' => 'image',
              'instructions' => 'This image will show up to the side of the content. ',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5690e7d00202d',
                    'operator' => '!=',
                    'value' => 'center',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'preview_size' => 'large',
              'library' => 'all',
              'return_format' => 'url',
              'min_width' => 0,
              'min_height' => 0,
              'min_size' => 0,
              'max_width' => 0,
              'max_height' => 0,
              'max_size' => 0,
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '56921412370af',
          'name' => 'sp-features',
          'label' => 'Features + Video',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_569df935ca953',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_568f8ea9ace2d',
              'label' => 'Heading',
              'name' => 'heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_568f8ed7ace2e',
              'label' => 'Intro Text',
              'name' => 'intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_568f8f17ace2f',
              'label' => 'Features',
              'name' => 'features',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_569df9c1ca954',
              'min' => '',
              'max' => '',
              'layout' => 'table',
              'button_label' => 'Add Feature',
              'sub_fields' => array (
                array (
                  'key' => 'field_569df9c1ca954',
                  'label' => 'Feature',
                  'name' => 'feature',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => 35,
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_569df9e4ca955',
                  'label' => 'Description',
                  'name' => 'description',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => 65,
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              ),
            ),
            array (
              'key' => 'field_569dfa14ca956',
              'label' => 'Video',
              'name' => 'video',
              'type' => 'textarea',
              'instructions' => 'Paste the embed code for the video you want to display here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 55,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => 5,
              'new_lines' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e1010cccc2',
              'label' => 'Video Caption',
              'name' => 'video_caption',
              'type' => 'text',
              'instructions' => 'This text will be shown below the video.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 45,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e4b455831e',
              'label' => 'Background style',
              'name' => 'background_style',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'gradient' => 'Gradient',
                'default' => 'Default',
              ),
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => 'default',
              'layout' => 'horizontal',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '569e152ffed0c',
          'name' => 'sp-cta',
          'label' => 'Call to Action',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_569e152ffed0d',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_569e152ffed0e',
              'label' => 'When this button is clicked, what happens?',
              'name' => 'cta_action',
              'type' => 'select',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'popover' => 'A pop-over box displays.',
                'page' => 'The user goes to a new page.',
              ),
              'default_value' => array (
                'page' => 'page',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'placeholder' => '',
              'disabled' => 0,
              'readonly' => 0,
            ),
            array (
              'key' => 'field_569e152ffed0f',
              'label' => 'Button Text',
              'name' => 'cta_text',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e152ffed10',
              'label' => 'URL to Open on Click',
              'name' => 'cta_link',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_569e152ffed0e',
                    'operator' => '==',
                    'value' => 'page',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '569e1e668f12d',
          'name' => 'sp-about',
          'label' => 'About Precision Nutrition',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_569e1fc18f12f',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_569e1fd28f130',
              'label' => 'Heading',
              'name' => 'heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e1fd98f131',
              'label' => 'Top Body Text',
              'name' => 'top_body_text',
              'type' => 'wysiwyg',
              'instructions' => 'This can be any copy. Typically, it\'s the PN intro: who we are, what we do, why we\'re different.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
            array (
              'key' => 'field_569e1ffb8f132',
              'label' => 'Team Heading',
              'name' => 'team_heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e20148f133',
              'label' => 'Team Members',
              'name' => 'team_members',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_569e20218f134',
              'min' => '',
              'max' => '',
              'layout' => 'row',
              'button_label' => 'Add Team Member',
              'sub_fields' => array (
                array (
                  'key' => 'field_569e20218f134',
                  'label' => 'Name',
                  'name' => 'name',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_569e20338f135',
                  'label' => 'Credentials',
                  'name' => 'credentials',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_569e203a8f136',
                  'label' => 'Position',
                  'name' => 'position',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_569e203f8f137',
                  'label' => 'Mini-Bio',
                  'name' => 'bio',
                  'type' => 'wysiwyg',
                  'instructions' => 'Aim for a single paragraph of 3–5 sentences.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'visual',
                  'toolbar' => 'basic',
                  'media_upload' => 0,
                ),
                array (
                  'key' => 'field_569e206e8f138',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'medium',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
            ),
            array (
              'key' => 'field_569e20d28f139',
              'label' => 'Credibility Heading',
              'name' => 'credibility_heading',
              'type' => 'text',
              'instructions' => 'This shows above the partner logos.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Precision Nutrition has worked with...',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e21958f13a',
              'label' => 'Credibility Logos',
              'name' => 'credibility_logos',
              'type' => 'image',
              'instructions' => 'Logos on a transparent background is ideal. (PNG format.)',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '569e4fa54056f',
          'name' => 'sp-pricing',
          'label' => 'Pricing',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_569e4fa540570',
              'label' => 'Which phases is this block visible during?',
              'name' => 'visible_phases',
              'type' => 'checkbox',
              'instructions' => 'If no boxes are checked, this block will never be visible.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'presale' => 'Presale',
                'sale' => 'Sale',
                'postsale' => 'Post-Sale',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 1,
            ),
            array (
              'key' => 'field_569e4fa540571',
              'label' => 'Heading',
              'name' => 'heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_569e4fa540574',
              'label' => 'Price Points',
              'name' => 'price_points',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => 'field_569e4fa540575',
              'min' => '',
              'max' => '',
              'layout' => 'table',
              'button_label' => 'Add Price Point',
              'sub_fields' => array (
                array (
                  'key' => 'field_569e4fa540575',
                  'label' => 'Price',
                  'name' => 'price',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_569e4fa540576',
                  'label' => 'Break',
                  'name' => 'break',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
    array (
      'key' => 'field_5692161ffa9af',
      'label' => 'Launch Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_56921642fa9b0',
      'label' => 'What date does the launch begin?',
      'name' => 'launch_start_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'Y-m-d',
      'return_format' => 'Ymd',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_56921d2a3a55d',
      'label' => 'What date does the launch end?',
      'name' => 'launch_end_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'Y-m-d',
      'return_format' => 'Ymd',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_56921800fa9b1',
      'label' => 'What time does the launch begin?',
      'name' => 'launch_start_time',
      'type' => 'text',
      'instructions' => 'NOTE: Use military time! If the sale starts at the beginning of the day, use 0:00. If it starts at the end, use 23:59.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0:00',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56921a77fa9b6',
      'label' => 'What time does the launch end?',
      'name' => 'launch_end_time',
      'type' => 'text',
      'instructions' => 'NOTE: Use military time! If the sale ends at midnight, it\'s probably easiest to use 23:59.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0:00',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_569218cdfa9b2',
      'label' => 'Launch Phases',
      'name' => 'launch_phases',
      'type' => 'repeater',
      'instructions' => 'You can create as many launch phases as you like. The can even overlap, technically, though that\'s probably going to be super confusing for both you and your customers.

To set phase-specific content, wrap it in a shortcode: <code>[sp phase="my_phase_name"]YOUR CONTENT[/sp]</code>

You can also make text visible during multiple phases with a comma-separated list: <code>[sp phase="my_phase_name, other_phase_name"]CONTENT[/sp]</code>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Add Row',
      'sub_fields' => array (
        array (
          'key' => 'field_56921916fa9b3',
          'label' => 'Phase Name',
          'name' => 'phase_name',
          'type' => 'text',
          'instructions' => 'Letters and underscores only (e.g. "my_phase_name"). Other characters will be stripped and it\'ll make your life harder when you have to edit things.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56921975fa9b4',
          'label' => 'How many days from launch does this phase begin?',
          'name' => 'phase_start_offset',
          'type' => 'number',
          'instructions' => 'For example, the presale launch might run for three days before the regular launch. That means it starts 3 days before the launch.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 0,
          'max' => '',
          'step' => 1,
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_569219dafa9b5',
          'label' => 'How many days from launch does this phase end?',
          'name' => 'phase_end_offset',
          'type' => 'number',
          'instructions' => 'For example, the presale launch might run for three days before the regular launch. That means it ends 0 days before the launch.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 0,
          'max' => '',
          'step' => 1,
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_569dde674e31b',
      'label' => 'Popover Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_569dde814e31c',
      'label' => 'Popover Heading',
      'name' => 'popover_heading',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_569ddf614e31d',
      'label' => 'Popover Body Text',
      'name' => 'popover_body_text',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'basic',
      'media_upload' => 0,
    ),
    array (
      'key' => 'field_569ddf854e31e',
      'label' => 'Popover Button Text',
      'name' => 'popover_button_text',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'sellaporter.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'permalink',
    1 => 'the_content',
    2 => 'excerpt',
    3 => 'custom_fields',
    4 => 'discussion',
    5 => 'comments',
    6 => 'revisions',
    7 => 'author',
    8 => 'format',
    9 => 'categories',
    10 => 'tags',
    11 => 'send-trackbacks',
  ),
  'active' => 1,
  'description' => '',
));

endif;
